package com.whf.springservice.dao.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sequence
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Sequence implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence.seq_name
     *
     * @mbg.generated
     */
    private String seqName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence.current_val
     *
     * @mbg.generated
     */
    private Integer currentVal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence.increment_val
     *
     * @mbg.generated
     */
    private Integer incrementVal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sequence
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence.seq_name
     *
     * @return the value of sequence.seq_name
     *
     * @mbg.generated
     */
    public String getSeqName() {
        return seqName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence.seq_name
     *
     * @param seqName the value for sequence.seq_name
     *
     * @mbg.generated
     */
    public void setSeqName(String seqName) {
        this.seqName = seqName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence.current_val
     *
     * @return the value of sequence.current_val
     *
     * @mbg.generated
     */
    public Integer getCurrentVal() {
        return currentVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence.current_val
     *
     * @param currentVal the value for sequence.current_val
     *
     * @mbg.generated
     */
    public void setCurrentVal(Integer currentVal) {
        this.currentVal = currentVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence.increment_val
     *
     * @return the value of sequence.increment_val
     *
     * @mbg.generated
     */
    public Integer getIncrementVal() {
        return incrementVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence.increment_val
     *
     * @param incrementVal the value for sequence.increment_val
     *
     * @mbg.generated
     */
    public void setIncrementVal(Integer incrementVal) {
        this.incrementVal = incrementVal;
    }
}