package com.whf.springservice.dao.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tm_course_record
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TmCourseRecord implements Serializable {
    /**
     * Database Column Remarks:
     *   会员ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_course_record.member_id
     *
     * @mbg.generated
     */
    private String memberId;

    /**
     * Database Column Remarks:
     *   老师id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_course_record.teacher_member_id
     *
     * @mbg.generated
     */
    private String teacherMemberId;

    /**
     * Database Column Remarks:
     *   课程id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_course_record.course_id
     *
     * @mbg.generated
     */
    private String courseId;

    /**
     * Database Column Remarks:
     *   课程时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_course_record.course_time
     *
     * @mbg.generated
     */
    private Date courseTime;

    /**
     * Database Column Remarks:
     *   课程名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_course_record.course_name
     *
     * @mbg.generated
     */
    private String courseName;

    /**
     * Database Column Remarks:
     *   课程状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_course_record.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * Database Column Remarks:
     *   教学类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_course_record.teacher_type
     *
     * @mbg.generated
     */
    private String teacherType;

    /**
     * Database Column Remarks:
     *   标签
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_course_record.lable
     *
     * @mbg.generated
     */
    private String lable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_course_record.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_course_record.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tm_course_record
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_course_record.member_id
     *
     * @return the value of tm_course_record.member_id
     *
     * @mbg.generated
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_course_record.member_id
     *
     * @param memberId the value for tm_course_record.member_id
     *
     * @mbg.generated
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_course_record.teacher_member_id
     *
     * @return the value of tm_course_record.teacher_member_id
     *
     * @mbg.generated
     */
    public String getTeacherMemberId() {
        return teacherMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_course_record.teacher_member_id
     *
     * @param teacherMemberId the value for tm_course_record.teacher_member_id
     *
     * @mbg.generated
     */
    public void setTeacherMemberId(String teacherMemberId) {
        this.teacherMemberId = teacherMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_course_record.course_id
     *
     * @return the value of tm_course_record.course_id
     *
     * @mbg.generated
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_course_record.course_id
     *
     * @param courseId the value for tm_course_record.course_id
     *
     * @mbg.generated
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_course_record.course_time
     *
     * @return the value of tm_course_record.course_time
     *
     * @mbg.generated
     */
    public Date getCourseTime() {
        return courseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_course_record.course_time
     *
     * @param courseTime the value for tm_course_record.course_time
     *
     * @mbg.generated
     */
    public void setCourseTime(Date courseTime) {
        this.courseTime = courseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_course_record.course_name
     *
     * @return the value of tm_course_record.course_name
     *
     * @mbg.generated
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_course_record.course_name
     *
     * @param courseName the value for tm_course_record.course_name
     *
     * @mbg.generated
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_course_record.status
     *
     * @return the value of tm_course_record.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_course_record.status
     *
     * @param status the value for tm_course_record.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_course_record.teacher_type
     *
     * @return the value of tm_course_record.teacher_type
     *
     * @mbg.generated
     */
    public String getTeacherType() {
        return teacherType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_course_record.teacher_type
     *
     * @param teacherType the value for tm_course_record.teacher_type
     *
     * @mbg.generated
     */
    public void setTeacherType(String teacherType) {
        this.teacherType = teacherType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_course_record.lable
     *
     * @return the value of tm_course_record.lable
     *
     * @mbg.generated
     */
    public String getLable() {
        return lable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_course_record.lable
     *
     * @param lable the value for tm_course_record.lable
     *
     * @mbg.generated
     */
    public void setLable(String lable) {
        this.lable = lable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_course_record.create_time
     *
     * @return the value of tm_course_record.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_course_record.create_time
     *
     * @param createTime the value for tm_course_record.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_course_record.update_time
     *
     * @return the value of tm_course_record.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_course_record.update_time
     *
     * @param updateTime the value for tm_course_record.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}