package com.whf.springservice.dao.mapper;

import com.whf.springservice.dao.entity.Sequence;
import com.whf.springservice.dao.entity.SequenceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SequenceMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence
     *
     * @mbg.generated
     */
    String nextval();
}